### ISSUE TITLE
Add support for Mediaflux

### ISSUE THREAD

**Issue by kcho** [PREDICT-DPACC/lochness#12]
work in progress in `dev/kcho/mediaflux` branch
- https://github.com/PREDICT-DPACC/lochness/tree/dev/kcho%2Fmediaflux

line comparison
- https://github.com/PREDICT-DPACC/lochness/compare/master...PREDICT-DPACC:dev/kcho/mediaflux

**Comment by tashrifbillah** [comment]
I see some work here. So where should I start--from here or fresh?

**Comment by kcho** [comment]
@tashrifbillah I have not worked much on this branch, so have a look and feel free to start over if you think it's simpler for you to start over!

**Comment by tashrifbillah** [comment]
I shall start afresh but from which branch?

**Comment by kcho** [comment]
Create a new branch if you're starting fresh please. I'll remove this branch https://github.com/PREDICT-DPACC/lochness/tree/dev/kcho%2Fmediaflux
