### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by tashrifbillah** [PREDICT-DPACC/lochness#15]
Hi @kcho ,

Why are there three identical lines [here](https://github.com/PREDICT-DPACC/lochness/blob/master/lochness/box/__init__.py#L302)?

**Comment by kcho** [comment]
My bad - thanks for noticing this. I'll remove them in the next push.

**Comment by tashrifbillah** [comment]
No worries, I can do this and close this via.

**Comment by tashrifbillah** [comment]
Fixed in https://github.com/PREDICT-DPACC/lochness/commit/646cc456ddcee1dc9176a52b11ed8fe97a393432
