### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by tashrifbillah** [PREDICT-DPACC/lochness#16]
What is [this](https://github.com/PREDICT-DPACC/lochness/blob/master/lochness/config/__init__.py#L29) block doing? End result of the block `modality_dict` is not used anywhere, is it? If yes, we need to remove dead codes.

@kcho

**Comment by kcho** [comment]
This lines are updating box file pattern attributes to the Lochness object. (these lines still updates the attributes even without respecification of the attribute of the object)

It loads `file patterns` from the configuration file to catch the file naming in the file sources on the box.
