### ISSUE TITLE
Remove space from a key in config

### ISSUE THREAD

**Issue by tashrifbillah** [PREDICT-DPACC/lochness#18]
`file patterns` should be one word. More appropriate could be just `datatype`.

https://github.com/PREDICT-DPACC/lochness/blob/master/docs/source/configuration_file.rst#box-base

**Comment by kcho** [comment]
I agree on the one word. It's not exactly the `datatype`. How about `file_patterns`? `file_datatype`?

**Comment by tashrifbillah** [comment]
`file_patterns` sounds okay.

**Comment by kcho** [comment]
I'll will make an update about this in the Redcap Data Capture PR and close this issue.

**Comment by kcho** [comment]
Changes made. Thanks for the comment, Tashrif.
https://github.com/PREDICT-DPACC/lochness/pull/13/commits/e6a9f4078a953f0100a52449e76ac184209cfbb7
