### ISSUE TITLE
Common string between metadata and keyring_file

### ISSUE THREAD

**Issue by tashrifbillah** [PREDICT-DPACC/lochness#19]
Example:
* `redcap.hcpep` string from metadata must exist in a subsection in the keyring file
* `xnat` string from metadata must exist in a subsection in the keyring file (does not necessarily have to be `xnat.hcpep`)

metadata file:
```
Active,Consent,Subject ID,XNAT,REDCap
1,2017-02-09,subject1001,xnat:HCPEP-BWH:1001,redcap.hcpep:1001_1
1,2017-02-09,subject1002,xnat:HCPEP-BWH:1002,redcap.hcpep:1002_1
```

keyring file:
```
{
  "redcap.hcpep": {
    "URL": "https://redcap.partners.org/redcap",
    "USERNAME": "tbillah",
    "PASSWORD": "whatever"
  },
   "xnat": {
    "URL": "https://hcpep-xnat.bwh.harvard.edu/",
    "USERNAME": "tbillah",
    "PASSWORD": "whatever"
  }
}
```

cc @kcho

**Comment by kcho** [comment]
Thinking back on the keyring file structure, how would we enter `TOKENS` and `PASSWORDS` if we have more than one XNAT source?

**Comment by tashrifbillah** [comment]
Then we shall need two unique identifiers:
* `xnat.hi`
* `hello-xnat`

My point is it wouldn't have to be `.` separated or named exactly like `f'{source}.{study}'`

**Comment by tashrifbillah** [comment]
Adequately documented in 
https://github.com/PREDICT-DPACC/lochness/blob/373beda14d9ff2147e450136ed84c11eff828091/docs/source/mediaflux.md#appendix
