### ISSUE TITLE
[Question] Pulling data from multiple sites: multiple lochness.yml

### ISSUE THREAD

**Issue by tashrifbillah** [PREDICT-DPACC/lochness#20]
Must not we need two `lochness.yml`--one for BWH and one for MGH to sync the following? In other words, two `sync.py`--one with `--studies BWH` and one with `studies MGH` must be run.

```
# Mediaflux remote
/proj/namespace/all_BWH_surveys/{subid}/*csv
/proj/namespace/all_MGH_surveys/{subid}/*csv
/proj/namespace/BWH_Zoom/{subid}/Zoom/*mov
/proj/namespace/MGH_Actigraphy/{subid}/GENEActiv/*bin


# Mediaflux local
PHOENIX_ROOT/GENERAL/BWH/{subid}/surveys/*csv
PHOENIX_ROOT/GENERAL/MGH/{subid}/surveys/*csv
PHOENIX_ROOT/PROTECTED/BWH/{subid}/video/*mov
PHOENIX_ROOT/PROTECTED/MGH/{subid}/actigraphy/*bin
```

I am raising this question because, as an example, in [this box config](https://github.com/PREDICT-DPACC/lochness/blob/master/docs/source/configuration_file.rst#box-base), we nowhere mention the study name.

@kcho

**Comment by kcho** [comment]
As far as I understand, there should be a single `config.yml` file, which should be able to have information registered for more than one study. 

And the structure is more like 
`PHOENIX_ROOT/GENERAL/${STUDY}/${SUBJECT}`
not `PHOENIX_ROOT/${STUDY}/GENERAL/${SUBJECT}`

And this `study` information should be included in one of the attributes in the `Lochness` variable passed to  `lochness.module.sync`. 

Please correct me if I'm wrong.

**Comment by tashrifbillah** [comment]
> And the structure is more like

Sure, I have corrected in my description.

> information should be included in one of the attributes in the Lochness variable

Lochness variable echoes `lochness.yml` and I don't find any `study` name there.

**Comment by kcho** [comment]
![Pasted_Image_4_20_21__1_34_PM](https://user-images.githubusercontent.com/3075783/115439938-21180a00-a1dd-11eb-828c-22c4794d6bcf.png)

**Comment by tashrifbillah** [comment]
@kcho , can you comment on the last bullet point of [Appendix](https://github.com/PREDICT-DPACC/lochness/blob/373beda14d9ff2147e450136ed84c11eff828091/docs/source/mediaflux.md#appendix)?

I have provided two files--`.lochness.json` and `config.yml` for pulling data from multiple sites altogether.

**Comment by kcho** [comment]
> @kcho , can you comment on the last bullet point of [Appendix](https://github.com/PREDICT-DPACC/lochness/blob/373beda14d9ff2147e450136ed84c11eff828091/docs/source/mediaflux.md#appendix)?
> 
> I have provided two files--`.lochness.json` and `config.yml` for pulling data from multiple sites altogether.

Amazing documentation BTW👌

Only a few comments
- `config.yml`
  - The items under `file_patterns` could be indented for readability
  -  `namespace` under each sites is the root directory, correct? 
- `.lochness.json` should be `.lochness.enc`

**Comment by tashrifbillah** [comment]
> Amazing documentation BTW👌

Thank you for reading it.

> namespace under each site is the root directory, correct?

Yes

> The items under file_patterns could be indented for readability

You are so right! My local files are properly indented. I wonder how it has not been in the doc.

> .lochness.json should be .lochness.enc

I have provided a human-readable keyring_file so I think it should be `.lochness.json`.

**Comment by tashrifbillah** [comment]
I have fixed the indentation and made you a co-author. Feel free to take a second look. Thank you for your time.

**Comment by kcho** [comment]
> I have provided a human-readable keyring_file so I think it should be .lochness.json.

I understand you've provided the `lochness.json` to make users understand how the keyring should be structured. I thought a few people who read this documentation may end up copy and pasting your example, using `.lochenss.json` in their `sync.py` execution.

**Comment by tashrifbillah** [comment]
[Here](https://github.com/PREDICT-DPACC/lochness/blob/tbillah/mediaflux/docs/source/mediaflux.md#keyring-file) I have asked to encrypt it, thanks.
