### ISSUE TITLE
Add support for DaRIS

### ISSUE THREAD

**Issue by sbouix** [PREDICT-DPACC/lochness#5]

**Comment by kcho** [comment]
Meeting on Friday, April 16, 2021
- We have a clearer picture of the DaRIS usage. About time to build a module for this.

**Comment by sbouix** [comment]
I think @justintbaker was sent some instructions. Otherwise, you try to reach out to Wilson at unimelb.

**Comment by sbouix** [comment]
Also look here:
https://github.com/uom-daris

**Comment by tashrifbillah** [comment]
> Otherwise, you try to reach out to Wilson at unimelb.

Here is a useful hack around having to open another account with their system to reach Wilson:

<details><summary>Hack</summary>

Email uni-services@unimelb.edu.au with the string `Ref:MSG28119649` at the bottom of your email, all the way after signature. Thus our questions will be grouped under a previous ticket and so we can continue asking the email just like with do with HPC and RCC. Notably, that is the only ticket we have with them which was opened to generate us Mediaflux login.

</details>

**Comment by kcho** [comment]
WIP
https://github.com/PREDICT-DPACC/lochness/pull/24
